Option Strict Off
Option Explicit On
Imports System.IO
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports Microsoft.VisualBasic.ApplicationServices

Namespace My

    'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
    ' or if you encounter build errors in this file, go to the Project Designer
    ' (go to Project Properties or double-click the My Project node in
    ' Solution Explorer), and make changes on the Application tab.
    '
    Partial Friend Class MyApplication

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = False
            Me.EnableVisualStyles = True
            Me.SaveMySettingsOnExit = True
            Me.ShutdownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
        End Sub

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Protected Overrides Sub OnCreateMainForm()
            Me.MainForm = Global.monerospelunker.Form1
        End Sub

        Private Sub MyApplication_Startup(sender As Object, e As StartupEventArgs) Handles Me.Startup
            If My.Computer.FileSystem.FileExists("monerospelunker.conf") Then
                Try
                    ' Open the file using a stream reader.
                    Using sr As New StreamReader("monerospelunker.conf")
                        Dim line As String
                        ' Read the stream to a string and write the string to the console.
                        line = sr.ReadToEnd()
                        Form1.TextBoxPoolAddress.Text = line.Split(New Char() {"=", vbCrLf})(1)
                        Form1.TextBoxXmrAddress.Text = line.Split(New Char() {"=", vbCrLf})(3)
                        Form1.TextBoxThreads.Text = line.Split(New Char() {"=", vbCrLf})(5)
                        Console.WriteLine(line)
                    End Using
                Catch e1 As Exception
                    Console.WriteLine("The file could not be read:")
                    Console.WriteLine(e1.Message)
                End Try

            Else
                MsgBox("It looks like this is your first time running monerospelunker (or you deleted your monerospelunker.conf file). Make sure you set your own Monero address. After running once a monerospelunker.conf file will be created that will save your pool, address, and number of threads; you can delete this file at any time to reset the default settings.")
            End If
        End Sub

    End Class
End Namespace
